### ISSUE TITLE
Concrete example and Monaco React

### ISSUE THREAD

**Issue by theogiraudet** [CodinGame/monaco-languageclient-react#18]
Hello!
There is a concrete example to connect a language server (through websocket) with this library?
Because the Readme does not seems to be up to date (absence of `languageServerConfig`, `getSecurityToken` and `languageServerUrl` properties).

Other question, is this library compatible with https://github.com/CodinGame/monaco-editor-react to add a custom language to the React editor?

Thanks!

**Comment by CGNonofr** [comment]
Hello,

You're right, the README is not up to date, will update

All the `@codingame/monaco-*` libraries are designed to work together, but it's for internal use, you are free to use it but we can't really provide support on it.

**Comment by theogiraudet** [comment]
Okay I see, thanks for your answer!
